org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

group = com.github.sakuraryoko
mod_id = malitest
mod_name = MaLiTest
author = sakura-ryoko
mod_file_name = malitest-fabric

# Current mod version
mod_version = 0.2.2

# Required malilib version
malilib_version = 1.21-0.21.9

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version_out = 1.21
minecraft_version = 1.21
mappings_version = 1.21+build.9

fabric_loader_version = 0.16.14
mod_menu_version = 11.0.1
fabric_api_version = 0.102.0+1.21
